Feature/allow long fir
project8/locust_mc pull request #193
Opened 2021-05-17 15:01 UTC by pslocum

These changes include an option "allow-fast-sampling" (default=false) to use fast sampling relative to FIR duration.  In 30 GHz sampling tests using the analytic plane-wave transmitter, the output frequency looks correct, but there is some loss in detected power.  This is likely due to a loss of smooth phase variation between samples inside the FIR convolution.    

If we want to try a high-fidelity fast sampling test in the FSCD, then we probably need a shorter duration FIR to fit the short sampling interval.  On the other hand, if we are only checking output frequencies and features (and not necessarily absolute detected power), then these changes might be sufficient.

2021-05-19 00:34 UTC, psurukuc commented
Hi Penny, thanks for the edit. Looks like this modification would necessarily just make the ElementFIRBuffer used in convolution longer ? For a full convolution with proper sampling, we will probably need to make the FIR binwidth finer. I still don't understand why the power is lower. Given that the only change this would make is make ElementFIRBuffer I assume the FIR still contains all the needed information. I don't completely understand what you mean by "shorter duration FIR".

2021-05-21 19:04 UTC, pslocum commented
Thanks for taking a look at this and for chatting.  I think we can enforce
the smoother phase variation along with faster sampling, and then see how
things are looking at that point.

On Tue, May 18, 2021 at 8:34 PM Pranava Teja Surukuchi <
***@***.***> wrote:

> Hi Penny, thanks for the edit. Looks like this modification would
> necessarily just make the ElementFIRBuffer used in convolution longer ? For
> a full convolution with proper sampling, we will probably need to make the
> FIR binwidth finer. I still don't understand why the power is lower. Given
> that the only change this would make is make ElementFIRBuffer I assume the
> FIR still contains all the needed information. I don't completely
> understand what you mean by "shorter duration FIR".
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/project8/locust_mc/pull/193#issuecomment-843656839>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABVBROJNTBT5PGX5JZ54TRLTOMBRJANCNFSM45AUNKNQ>
> .
>

2021-05-24 16:41 UTC, pslocum commented
With "allow-fast-sampling"=true for zero modulation, we now have the same power in the carrier as for "allow-fast-sampling"=false (plots below).  This improvement comes from enforcing smooth phase advancement of the incident field inside the FIR convolution.  For fields with moderate modulation (Trap 10 pitch=88.5, below), we are seeing slightly more power in sidebands and slightly less in the carrier for "allow-fast-sampling"=true.  

We may want to make "allow-fast-sampling" to default to true.  I think it is a better representation of the modulating incident fields.  

![newsampling_PlaneWave](https://user-images.githubusercontent.com/6953145/119378526-586e5080-bc8c-11eb-9244-7496bacb177d.png)
![oldsampling_PlaneWave](https://user-images.githubusercontent.com/6953145/119378528-5906e700-bc8c-11eb-9920-60b677c6ef8c.png)
![newsampling_Trap10_pitch88 5](https://user-images.githubusercontent.com/6953145/119379171-23163280-bc8d-11eb-8a90-17e7b3df0563.png)
![oldsampling_Trap10_pitch88 5](https://user-images.githubusercontent.com/6953145/119379173-23163280-bc8d-11eb-820e-7bb4f16e3acf.png)

2021-05-25 00:55 UTC, psurukuc commented on Source/Generators/LMCArraySignalGenerator.cc
> +    double ArraySignalGenerator::GetFIRSample(int nFilterBins, int nFilterBinsRequired, double dtFilter, unsigned channel, unsigned element)
I think nFilterSize doesn't need to passed as an argument anymore to GetFIRSample

2021-05-25 00:56 UTC, psurukuc commented on Source/Generators/LMCArraySignalGenerator.cc
> +    bool ArraySignalGenerator::DriveAntenna(FILE *fp, int startingIndex, unsigned index, Signal* aSignal, int nFilterBins, int nFilterBinsRequired, double dtFilter)
Same here

2021-05-25 00:56 UTC, psurukuc commented on Source/Generators/LMCArraySignalGenerator.cc
> + 	            double VoltageFIRSample = GetFIRSample(nFilterBins, nFilterBinsRequired, dtFilter, channelIndex, elementIndex);
Same here

2021-05-25 00:56 UTC, psurukuc commented on Source/Generators/LMCArraySignalGenerator.cc
> +        		DriveAntenna(fp, PreEventCounter, index, aSignal, nFilterBins, nFilterBinsRequired, dtFilter);
Same as above

2021-05-25 00:57 UTC, psurukuc commented on Source/Generators/LMCArraySignalGenerator.hh
> +            double GetFIRSample(int nFilterBins, int nFilterBinsRequired, double dtfilter, unsigned channel, unsigned patch);
Same here

2021-05-25 00:57 UTC, psurukuc commented on Source/Generators/LMCArraySignalGenerator.hh
> +            bool DriveAntenna(FILE *fp, int startingIndex, unsigned index, Signal* aSignal, int nFilterBins, int nFilterBinsRequired, double dtfilter);
Same here

2021-05-25 00:57 UTC, psurukuc commented on Source/Generators/LMCArraySignalGenerator.cc
> +                    		if (DriveAntenna(fp, startingIndex, index, aSignal, nFilterBins, nFilterBinsRequired, dtFilter))
Here as well

2021-05-25 00:58 UTC, psurukuc requested changes
Looks good Penny. Just for cleaner code you may want to remove "nFilterBins" as argument for GetFIRSample and DriveAntenna functions.

2021-06-02 23:09 UTC, psurukuc approved these changes
Looks good to me penny, thanks for doing this.

2021-06-03 14:37 UTC, merged